using System.Collections.Generic;
using Exiled.API.Enums;

namespace Fentanyl_ReactorUpdate.API.Classes;

public class Enmm
{
    public Dictionary<ItemType, string> ItemTranslations = new()
    {
        { ItemType.Radio, "Funkgerät" },
        { ItemType.Painkillers, "Schmerzmittel" },
        { ItemType.GunCOM15, "Pistole COM15" },
        { ItemType.Coin, "Münze" },
        { ItemType.GunCOM18, "Pistole COM18" },
        { ItemType.GunFSP9, "Maschinenpistole FSP9" },
        { ItemType.GunCrossvec, "Maschinenpistole Crossvec" },
        { ItemType.GunE11SR, "Sturmgewehr E11-SR" },
        { ItemType.GunShotgun, "Schrotflinte" },
        { ItemType.GunLogicer, "Maschinengewehr Logicer" },
        { ItemType.ParticleDisruptor, "Partikelstörer" },
        { ItemType.Flashlight, "Taschenlampe" },
        { ItemType.GrenadeFlash, "Blendgranate" },
        { ItemType.GrenadeHE, "Handgranate" },
        { ItemType.KeycardChaosInsurgency, "Zugangskarte der Chaos Insurgency" },
        { ItemType.Medkit, "Medikit" },
        { ItemType.Adrenaline, "Adrenalin" },
        { ItemType.SCP500, "SCP-500" },
        { ItemType.SCP207, "SCP-207" },
        { ItemType.SCP2176, "SCP-2176" },
        { ItemType.SCP1576, "SCP-1576" },
        { ItemType.SCP268, "SCP-268" },
        { ItemType.SCP1853, "SCP-1853" },
        { ItemType.Jailbird, "Jailbird" },
        { ItemType.KeycardJanitor, "Zugangskarte Hausmeister" },
        { ItemType.KeycardScientist, "Zugangskarte Wissenschaftler" },
        { ItemType.KeycardResearchCoordinator, "Zugangskarte Forschungskoordinator" },
        { ItemType.KeycardZoneManager, "Zugangskarte Zonenmanager" },
        { ItemType.KeycardGuard, "Zugangskarte Wachmann" },
        { ItemType.KeycardContainmentEngineer, "Zugangskarte Eindämmungsingenieur" },
        { ItemType.KeycardMTFOperative, "Zugangskarte MTF-Operator" },
        { ItemType.KeycardMTFCaptain, "Zugangskarte MTF-Captain" },
        { ItemType.KeycardFacilityManager, "Zugangskarte Einrichtungsleiter" },
        { ItemType.KeycardO5, "Zugangskarte O5" }
    };
    public Dictionary<RoomType, string> RoomTranslations = new()
    {
        { RoomType.LczClassDSpawn, "LCZ - Klass-D-Spawn" },
        { RoomType.LczCafe, "LCZ - Cafeteria" },
        { RoomType.Lcz330, "LCZ - SCP-330" },
        { RoomType.Lcz173, "LCZ - SCP-173" },
        { RoomType.LczCrossing, "LCZ - Kreuzung" },
        { RoomType.LczStraight, "LCZ - Weg" },
        { RoomType.LczTCross, "LCZ - T-Kreuzung" },
        { RoomType.LczArmory, "LCZ - Waffenkammer" },
        { RoomType.Lcz914, "LCZ - SCP-914" },
        { RoomType.LczGlassBox, "LCZ - Gläserner Raum" },
        { RoomType.LczToilets, "LCZ - Toiletten" },
        { RoomType.LczCheckpointA, "LCZ - Kontrollpunkt A" },
        { RoomType.LczCheckpointB, "LCZ - Kontrollpunkt B" },
        { RoomType.Hcz049, "HCZ - SCP-049" },
        { RoomType.Hcz079, "HCZ - SCP-079" },
        { RoomType.Hcz096, "HCZ - SCP-096" },
        { RoomType.Hcz106, "HCZ - SCP-106" },
        { RoomType.HczArmory, "HCZ - Waffenkammer" },
        { RoomType.HczNuke, "HCZ - Atombombenraum" },
        { RoomType.HczCrossRoomWater, "HCZ - Wasserkontrollbereich" },
        { RoomType.HczTesla, "HCZ - Teslagitter" },
        { RoomType.HczStraight, "HCZ - Weg" },
        { RoomType.HczStraightC, "HCZ - Weg" },
        { RoomType.HczStraightVariant, "HCZ - Weg" },
        { RoomType.HczStraightPipeRoom, "HCZ - Weg" },
        { RoomType.HczEzCheckpointA, "HCZ - Kontrollpunkt A" },
        { RoomType.HczEzCheckpointB, "HCZ - Kontrollpunkt B" },
        { RoomType.HczCrossing, "HCZ - Kreuzung" },
        { RoomType.HczCurve, "HCZ - Kurve" },
        { RoomType.HczIntersection, "HCZ - T-Kreuzung" },
        { RoomType.EzCollapsedTunnel, "EZ - Eingestürzter Tunnel" },
        { RoomType.EzGateA, "EZ - Tor A" },
        { RoomType.EzGateB, "EZ - Tor B" },
        { RoomType.EzStraight, "EZ - Weg" },
        { RoomType.EzStraightColumn, "EZ - Weg" },
        { RoomType.EzChef, "EZ - Büros" },
        { RoomType.EzCurve, "EZ - Kurve" },
        { RoomType.EzTCross, "EZ - T-Kreuzung" },
        { RoomType.EzCrossing, "EZ - Kreuzung" },
        { RoomType.EzIntercom, "EZ - Interkom" },
        { RoomType.EzDownstairsPcs, "EZ - PC-Raum (unten)" },
        { RoomType.EzUpstairsPcs, "EZ - PC-Raum (oben)" },
        { RoomType.EzShelter, "EZ - Evakuierungsshelter" },
        { RoomType.EzVent, "EZ - Lüftungsschacht" },
        { RoomType.Surface, "Oberfläche" },
    };

}